apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      restartPolicy: Always

      containers:
        - name: superset-app
          image: $ACR_LOGIN_SERVER/superset_base
          args: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
          ports:
          - containerPort: 8088
          envFrom:
          - configMapRef:
              name: superset-environment-variables
          env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: password

        - name: superset-worker
          image: $ACR_LOGIN_SERVER/superset_base
          args: ["/app/docker/docker-bootstrap.sh", "worker"]
          envFrom:
          - configMapRef:
              name: superset-environment-variables
          env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: password

        - name: superset-worker-beat
          image: $ACR_LOGIN_SERVER/superset_base
          args: ["/app/docker/docker-bootstrap.sh", "beat"]
          envFrom:
          - configMapRef:
              name: superset-environment-variables
          env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-credentials
                key: password
